# Taichi Dockerfile for development
FROM nvidia/cuda:11.3.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
CMD /bin/bash

USER root
# This installs Python 3.6.9 by default. Once the
# docker image is upgraded to Ubuntu 20.04 this will
# install Python 3.8 by default

# This installs Python 3.6.9 by default. Once the
# docker image is upgraded to Ubuntu 20.04 this will
# install Python 3.8 by default
RUN apt-get update && \
    apt-get install -y software-properties-common \
                       python3-pip \
                       libtinfo-dev \
                       libx11-dev \
                       libxrandr-dev \
                       libxinerama-dev \
                       libxcursor-dev \
                       libxi-dev \
                       libglu1-mesa-dev \
                       freeglut3-dev \
                       mesa-common-dev \
                       libtinfo5 \
                       build-essential \
                       libssl-dev \
                       vim

# Install Taichi's Python dependencies
RUN python3 -m pip install --user setuptools astor pybind11 pylint sourceinspect
RUN python3 -m pip install --user pytest pytest-rerunfailures pytest-xdist yapf
RUN python3 -m pip install --user numpy GitPython coverage colorama autograd
RUN python3 -m pip install --user taichi

# add and enable the default user
# ARG USER2=rm3681
# RUN useradd -ms /bin/bash $USER2
ARG USER2=rm3681
ARG UID=1006
ARG GID=1006
RUN groupadd -g $GID -o $USER2
RUN useradd -m -u $UID -g $GID -s /bin/bash $USER2

# Add Docker specific ENV
#make sure everything is in place
USER $USER2
ENV HOME /home/$USER2
ENV USER $USER2
WORKDIR $HOME
